// Typed pipeline steps. The intelligence (JD analysis, candidate match, CV /
// cover-letter generation) is stubbed behind these interfaces so the vertical
// slice compiles, deploys, and walks end-to-end today. Swap each stub for a
// real Claude-backed implementation later without changing the orchestrator.

export interface JobAnalysis {
  title: string;
  company: string;
  responsibilities: string[];
  requirements: string[];
  keywords: string[];
  seniority: string;
}

export interface MatchReport {
  score: number; // 0..1
  strengths: string[];
  gaps: string[];
}

export interface GeneratedCv {
  fileName: string;
  mimeType: string;
  contentBase64: string;
}

function hostOf(url: string): string {
  try {
    return new URL(url).hostname.replace(/^www\./, "");
  } catch {
    return "unknown-source";
  }
}

/** STUB — replace with a Claude-backed JD analysis over fetched job text. */
export function analyzeJobDescription(url: string, text?: string): JobAnalysis {
  const company = hostOf(url);
  return {
    title: text?.split("\n")[0]?.slice(0, 120) || `Role at ${company}`,
    company,
    responsibilities: ["(placeholder) analyze responsibilities from JD"],
    requirements: ["(placeholder) extract requirements from JD"],
    keywords: [company],
    seniority: "unspecified",
  };
}

/** STUB — replace with a grounded candidate-to-job match against evidence. */
export function matchCandidate(analysis: JobAnalysis): MatchReport {
  return {
    score: 0.5,
    strengths: [`(placeholder) strengths for ${analysis.title}`],
    gaps: ["(placeholder) gaps to address"],
  };
}

/** STUB — replace with a real tailored CV rendered to PDF. */
export function buildCv(analysis: JobAnalysis, match: MatchReport): GeneratedCv {
  const body = [
    `PLACEHOLDER CV`,
    `Target role: ${analysis.title}`,
    `Company: ${analysis.company}`,
    `Match score: ${(match.score * 100).toFixed(0)}%`,
    ``,
    `Strengths:`,
    ...match.strengths.map((s) => `  - ${s}`),
    ``,
    `Gaps:`,
    ...match.gaps.map((s) => `  - ${s}`),
    ``,
    `Generated by Job Application Assistant (walking skeleton).`,
  ].join("\n");
  const safeCompany = analysis.company.replace(/[^a-z0-9]+/gi, "-").toLowerCase();
  return {
    fileName: `cv-${safeCompany}-placeholder.txt`,
    mimeType: "text/plain",
    contentBase64: Buffer.from(body, "utf8").toString("base64"),
  };
}
